src/Entity/Film.php
<?php

namespace App\Entity;

use App\Repository\FilmRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FilmRepository::class)]
class Film
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Nom = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $annee_sortie = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Genre = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Realisateur $realisateur = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): static
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getAnneeSortie(): ?string
    {
        return $this->annee_sortie;
    }

    public function setAnneeSortie(?string $annee_sortie): static
    {
        $this->annee_sortie = $annee_sortie;

        return $this;
    }

    public function getGenre(): ?string
    {
        return $this->Genre;
    }

    public function setGenre(?string $Genre): static
    {
        $this->Genre = $Genre;

        return $this;
    }

    public function getRealisateur(): ?Realisateur
    {
        return $this->realisateur;
    }

    public function setRealisateur(?Realisateur $realisateur): static
    {
        $this->realisateur = $realisateur;

        return $this;
    }
}

src/Form/FilmType.php
<?php

namespace App\Form;

use App\Entity\Film;
use App\Entity\Realisateur;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FilmType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('realisateur', EntityType::class, [
                'class' => Realisateur::class,
                'label' => 'Realisateur :    ',
                'choice_label' => function (Realisateur $realisateur) {
                    return $realisateur->getNom() . ' ' . $realisateur->getPrenom();
                }, 
                'placeholder' => 'Choisir un réalisateur',
                'required' => true,
                'attr' => [ 'style' => 'font-size: 1em; margin-bottom: 0.8em;' ]
            ])
            ->add('Nom', null, [
                'label' => 'Nom du Film : ',
                'attr' => [ 'style' => 'font-size: 1em; margin-bottom: 0.8em;' ]
            ])
            ->add('annee_sortie', null, [
                'label' => 'Anne du sortie : ',
                'attr' => [ 'style' => 'font-size: 1em; margin-bottom: 0.8em;' ]
            ])
            ->add('Genre', null, [
                'label' => 'Genre du Film : ',
                'attr' => [ 'style' => 'font-size: 1em; margin-bottom: 1em;' ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Film::class,
        ]);
    }
}

src/Controller/FilmController.php
<?php

namespace App\Controller;

use App\Entity\Film;
use App\Form\FilmType;
use App\Repository\FilmRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/film')] # Toutes les connexions à la page 127.0.0.1:8000/film/* sont traités ici
final class FilmController extends AbstractController
{
    #[Route(name: 'app_film_index', methods: ['GET'])] # Traite les connexions à la page /film qui envoient formulaire GET
    public function index(FilmRepository $filmRepository): Response
    {
        return $this->render('film/index.html.twig', [
            'films' => $filmRepository->findAll(), # Envoie les informations des films pour leur affichage sur la page twig
        ]);
    }

    #[Route('/new', name: 'app_film_new', methods: ['GET', 'POST'])] # Traite les connexions à la page /film/new qui envoient un formulaire GET ou POST
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        # Gère le formulaire de création d'un film

        $film = new Film();
        $form = $this->createForm(FilmType::class, $film);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($film); # Enregistre des données en local
            $entityManager->flush(); # Synchronise la BDD avec les données locales

            return $this->redirectToRoute('app_film_index', [], Response::HTTP_SEE_OTHER); # En cas de formulaire valide redirige sur la page affichant tous les films
        }

        # Si aucun formulaire envoyé alors affiche la page du formulaire avec les informations voulues
        return $this->render('film/new.html.twig', [
            'film' => $film,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_film_show', methods: ['GET'])] # Traite les connexions à la page /film/{id} qui envoient un formulaire GET
    public function show(Film $film): Response
    {
        return $this->render('film/show.html.twig', [
            'film' => $film, # Envoie les informations du film pour leur affichage sur la page twig
        ]);
    }

    #[Route('/{id}/edit', name: 'app_film_edit', methods: ['GET', 'POST'])] # Traite les connexions à la page /film/{id}/edit qui envoient un formulaire GET ou POST
    public function edit(Request $request, Film $film, EntityManagerInterface $entityManager): Response
    {
        # Gère le formulaire d'édition d'un film

        $form = $this->createForm(FilmType::class, $film);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush(); # Synchronise la BDD avec les données locales

            return $this->redirectToRoute('app_film_index', [], Response::HTTP_SEE_OTHER);
        }

        # Envoie les informations nécessaire au bon affichage du formulaire et des données du film pour leur édition
        return $this->render('film/edit.html.twig', [
            'film' => $film,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_film_delete', methods: ['POST'])] # Traite les connexions à la page /film/{id} qui envoient un formulaire POST
    public function delete(Request $request, Film $film, EntityManagerInterface $entityManager): Response
    {
        # Gère la suppression d'un film de la BDD

        if ($this->isCsrfTokenValid('delete'.$film->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($film); # Supprime les données en local
            $entityManager->flush(); # Synchronise la BDD avec les données locales
        }

        return $this->redirectToRoute('app_film_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/film/_delete_form.html.twig
<form method="post" action="{{ path('app_film_delete', {'id': film.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ film.id) }}">
    <button class="btn" style="font-size: 1.2em; margin: 1em; margin-bottom: 0.2em;">Supprimer</button>
</form>

templates/film/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn" style="font-size: 1.2em; margin-bottom: 0.2em;">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/film/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Film{% endblock %}

{% block body %}
    <div style="position: absolute; top: 0; right: 0; margin: 1em;">
        <a href="{{ path('app_logout') }}" style="text-decoration: none; font-size: 16px;">Se déconnecter</a>
    </div>

    <h1>Edit Film</h1>

    {{ include('film/_form.html.twig', {'button_label': 'Mettre à jour', 'button_style': 'style="font-size: 1.2em; margin-bottom: 0.2em; display: flex"'}) }}
    {{ include('film/_delete_form.html.twig') }}

    <a href="{{ path('app_film_index') }}" style="font-size: 0.8em; color:black;">Retour à la liste</a>
{% endblock %}

templates/film/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des Films{% endblock %}

{% block body %}
    <div style="font-size: 1.2em;">
    <div style="position: absolute; top: 0; right: 0; margin: 1em;">
        <a href="{{ path('app_logout') }}" style="text-decoration: none; font-size: 16px;">Se déconnecter</a>
    </div>
    
    <h1>Liste des Films</h1>

    <table class="table" style="border-collapse: collapse; margin-bottom: 1em">
        <thead>
            <tr>
                <th style="border: 1px solid black; text-align: center; padding: 0.5em;">Realisateur</th>
                <th style="border: 1px solid black; text-align: center; padding: 0.5em;">Nom</th>
                <th style="border: 1px solid black; text-align: center; padding: 0.5em;">Annee_sortie</th>
                <th style="border: 1px solid black; text-align: center; padding: 0.5em;">Genre</th>
                <th style="border: 1px solid black; text-align: center; padding: 0.5em;">actions</th>
            </tr>
        </thead>
        <tbody>
        {% for film in films %}
            <tr>
                <td style="border: 1px solid black; text-align: center; padding: 0.5em;">{{ film.Realisateur.Nom ~ ' ' ~ film.Realisateur.Prenom }}</td>
                <td style="border: 1px solid black; text-align: center; padding: 0.5em;">{{ film.Nom }}</td>
                <td style="border: 1px solid black; text-align: center; padding: 0.5em;">{{ film.anneeSortie }}</td>
                <td style="border: 1px solid black; text-align: center; padding: 0.5em;">{{ film.Genre }}</td>
                <td style="border: 1px solid black; text-align: center; padding: 0.5em;">
                    <a href="{{ path('app_film_show', {'id': film.id}) }}">Développer</a>
                    <b> | </b>
                    <a href="{{ path('app_film_edit', {'id': film.id}) }}">Editer</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_film_new') }}"><button style="font-size: 1.2em; margin-bottom: 0.2em;">Ajouter un nouveau film</button></a>
    <br>
    <a href="{{ path('app_home_page') }}" style="font-size: 0.8em; color:black;">Retour à la page d'accueil</a>
    </div>
{% endblock %}

templates/film/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau Film{% endblock %}

{% block body %}
    <div style="position: absolute; top: 0; right: 0; margin: 1em;">
        <a href="{{ path('app_logout') }}" style="text-decoration: none; font-size: 16px;">Se déconnecter</a>
    </div>
    
    <h1>Créer un nouveau Film</h1>

    {{ include('film/_form.html.twig') }}

    <a href="{{ path('app_film_index') }}" style="font-size: 0.8em; color:black;">Retour à la liste</a>
{% endblock %}

templates/film/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Film{% endblock %}

{% block body %}
    <div style="position: absolute; top: 0; right: 0; margin: 1em;">
        <a href="{{ path('app_logout') }}" style="text-decoration: none; font-size: 16px;">Se déconnecter</a>
    </div>
    
    <h1>Film</h1>

    <table class="table">
        <tbody>
            <tr>
                <th style="text-align: left; padding: 0.2em;">Nom : </th>
                <td style="text-align: left; padding: 0.2em;">{{ film.Nom }}</td>
            </tr>
            <tr>
                <th style="text-align: left; padding: 0.2em;">Annee de sortie : </th>
                <td style="text-align: left; padding: 0.2em;">{{ film.anneeSortie }}</td>
            </tr>
            <tr>
                <th style="text-align: left; padding: 0.2em;">Genre : </th>
                <td style="text-align: left; padding: 0.2em;">{{ film.Genre }}</td>
            </tr>
        </tbody>
    </table>

    <div style="display: flex;">
        <a href="{{ path('app_film_edit', {'id': film.id}) }}"><button style="font-size: 1.2em; margin-bottom: 0.2em; margin-top: 1em;">Editer</button></a>
        {{ include('film/_delete_form.html.twig') }}
    </div>

    <a href="{{ path('app_film_index') }}" style="font-size: 0.8em; color:black;">Retour à la listet</a>
{% endblock %}